name: Flutter windows
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - run: flutter pub get
      - name: build web
        run: flutter build windows
      - name: install nsis
        run: sudo apt-get install -y nsis
#      - run: make
